Vagrant.configure("2") do |config|
    config.vm.box = "uwbbi/bionic-arm64"
    config.vm.provision "shell",
      inline: "sudo apt update; 
      sudo apt install --yes nginx;
      echo 'Hello world'
      "
end