Vagrant.configure("2") do |config|
    config.vm.box = "uwbbi/bionic-arm64"
    config.vm.provision "shell",
      inline: "echo 'Hello world'"
    
    config.vm.define "web" do |web|
      web.vm.box = "uwbbi/bionic-arm64"
      web.vm.provision "shell",
        inline: "sudo apt update; 
        sudo apt install --yes nginx;
        echo 'Hello world'"
    end
    
    config.vm.define "db" do |db|
      db.vm.box = "uwbbi/bionic-arm64"
    end
end